#!/usr/bin/env python3
"""Generate every derived file in this repository from contract.json.

    python3 tools/generate.py           # rewrite fixtures/ and generated/
    python3 tools/generate.py --check   # fail if anything committed is stale

Outputs:
    fixtures/<ID>.bin                   FlatBuffer encoded by flatc (reference encoder)
    generated/blorg_contract.h          kernel-safe C macros (routes, statuses, version)
    generated/blorg_contract_fixtures.h C/C++ test fixtures (driver sandbox tests)
    generated/blorg_contract.rs         Rust constants and fixtures (server-rs)

flatc comes from $FLATC or PATH and must be the version in FLATC_VERSION below,
since that is the encoder server-rs builds with.

Standard library only, so it runs unchanged on the ubuntu and windows runners.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FLATC_VERSION = "25.12.19"
BANNER = "@generated by tools/generate.py from contract.json -- do not edit by hand."


def load_contract() -> dict:
    return json.loads((ROOT / "contract.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# fixtures/*.bin
# ---------------------------------------------------------------------------

def flatc_binary() -> str:
    flatc = os.environ.get("FLATC") or shutil.which("flatc")
    if not flatc:
        sys.exit("flatc not found: set FLATC or put flatc %s on PATH" % FLATC_VERSION)
    version = subprocess.run([flatc, "--version"], capture_output=True, text=True, check=True).stdout
    if FLATC_VERSION not in version:
        sys.exit("flatc %s required (server-rs pins it), found: %s" % (FLATC_VERSION, version.strip()))
    return flatc


def encode_fixtures(contract: dict, out_dir: Path) -> dict[str, bytes]:
    flatc = flatc_binary()
    schema = ROOT / contract["schema"]["file"]
    encoded = {}
    with tempfile.TemporaryDirectory() as tmp:
        for fixture in contract["fixtures"]:
            source = Path(tmp) / (fixture["id"] + ".json")
            source.write_text(json.dumps(fixture["data"]), encoding="utf-8")
            subprocess.run(
                [flatc, "--binary", "--root-type", fixture["root_type"], "-o", tmp, str(schema), str(source)],
                check=True,
            )
            encoded[fixture["id"]] = (Path(tmp) / (fixture["id"] + ".bin")).read_bytes()
    for fixture_id, data in encoded.items():
        (out_dir / "fixtures" / (fixture_id + ".bin")).write_bytes(data)
    return encoded


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def c_string(text: str) -> str:
    """A C narrow string literal holding text's UTF-8 bytes, escaped so it is pure ASCII."""
    out = []
    for byte in text.encode("utf-8"):
        ch = chr(byte)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif 0x20 <= byte < 0x7F:
            out.append(ch)
        else:
            # Octal, not \x: a hex escape would swallow a following hex digit.
            out.append("\\%03o" % byte)
    return '"' + "".join(out) + '"'


def c_wide_string(text: str) -> str:
    """An L"..." literal holding text as UTF-16 code units (Windows wchar_t)."""
    out = []
    raw = text.encode("utf-16-le")
    for i in range(0, len(raw), 2):
        unit = raw[i] | (raw[i + 1] << 8)
        ch = chr(unit) if unit < 0x80 else None
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch is not None and 0x20 <= unit < 0x7F:
            out.append(ch)
        else:
            out.append("\\x%04x\" L\"" % unit)  # split so the next char can't extend the escape
    return 'L"' + "".join(out) + '"'


def _rust_escape(text: str) -> str:
    out = []
    for ch in text:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            out.append("\\u{%x}" % code)
    return '"' + "".join(out) + '"'


def byte_rows(data: bytes, indent: str) -> str:
    rows = []
    for i in range(0, len(data), 12):
        rows.append(indent + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    return "\n".join(rows)


def route_by_id(contract: dict) -> dict:
    return {route["id"]: route for route in contract["routes"]}


# ---------------------------------------------------------------------------
# generated/blorg_contract.h  (kernel-safe: macros only)
# ---------------------------------------------------------------------------

def render_c_header(contract: dict) -> str:
    v = contract["version"]
    lines = [
        "//",
        "// " + BANNER,
        "//",
        "// The server-rs <-> BlorgFS wire contract. Macros only, so it is safe to",
        "// include from kernel code. Route strings are literals so they can be",
        "// concatenated into a request format string at compile time.",
        "//",
        "",
        "#pragma once",
        "",
        "#define BLORG_CONTRACT_VERSION_MAJOR %d" % v["major"],
        "#define BLORG_CONTRACT_VERSION_MINOR %d" % v["minor"],
        "",
        "#define BLORG_CONTRACT_QUERY_PATH %s" % c_string(contract["transport"]["query_path_key"]),
        "#define BLORG_CONTRACT_MAX_BODY_BYTES %d" % contract["transport"]["max_body_bytes"],
        "#define BLORG_CONTRACT_MAX_HEADER_BYTES %d" % contract["transport"]["max_header_bytes"],
        "",
    ]
    for route in contract["routes"]:
        lines.append("#define BLORG_CONTRACT_ROUTE_%s %s" % (route["id"], c_string(route["path"])))
        lines.append("#define BLORG_CONTRACT_STATUS_%s_OK %d" % (route["id"], route["success_status"]))
    lines.append("")
    for error in contract["error_statuses"]:
        lines.append("#define BLORG_CONTRACT_STATUS_%s %d" % (error["id"], error["status"]))
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# generated/blorg_contract_fixtures.h  (tests only)
# ---------------------------------------------------------------------------

def render_c_fixtures(contract: dict, encoded: dict[str, bytes]) -> str:
    out = [
        "//",
        "// " + BANNER,
        "//",
        "// Golden fixtures for the driver's sandbox tests: the exact request bytes",
        "// the driver must send, and FlatBuffer bodies (encoded by flatc, the same",
        "// encoder family server-rs uses) with the values they must decode to.",
        "// Usermode tests only -- not for kernel code.",
        "//",
        "",
        "#pragma once",
        "",
        '#include "blorg_contract.h"',
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <wchar.h>",
        "",
        "typedef struct BLORG_CONTRACT_REQUEST",
        "{",
        "    const char* Id;",
        "    const wchar_t* Path;      // as the driver receives it from Windows",
        "    int HasRange;",
        "    uint64_t RangeFirst;      // inclusive",
        "    uint64_t RangeLast;       // inclusive",
        "    const char* Wire;         // exact bytes the driver must send",
        "} BLORG_CONTRACT_REQUEST;",
        "",
        "typedef struct BLORG_CONTRACT_FILE",
        "{",
        "    const wchar_t* Name;",
        "    uint64_t Size, Created, Modified, Accessed;",
        "} BLORG_CONTRACT_FILE;",
        "",
        "typedef struct BLORG_CONTRACT_SUBDIR",
        "{",
        "    const wchar_t* Name;",
        "    uint64_t Created, Modified, Accessed;",
        "} BLORG_CONTRACT_SUBDIR;",
        "",
        "typedef struct BLORG_CONTRACT_LISTING",
        "{",
        "    const char* Id;",
        "    const unsigned char* Bytes;",
        "    size_t ByteCount;",
        "    const BLORG_CONTRACT_FILE* Files;",
        "    size_t FileCount;",
        "    const BLORG_CONTRACT_SUBDIR* SubDirs;",
        "    size_t SubDirCount;",
        "} BLORG_CONTRACT_LISTING;",
        "",
        "typedef struct BLORG_CONTRACT_ENTRY",
        "{",
        "    const char* Id;",
        "    const unsigned char* Bytes;",
        "    size_t ByteCount;",
        "    uint64_t Size, Created, Modified, Accessed;",
        "    int Directory;",
        "} BLORG_CONTRACT_ENTRY;",
        "",
    ]

    out.append("static const BLORG_CONTRACT_REQUEST BlorgContractRequests[] =")
    out.append("{")
    for req in contract["requests"]:
        first, last = req.get("range", [0, 0])
        out.append("    { %s, %s, %d, %dULL, %dULL, %s }," % (
            c_string(req["id"]), c_wide_string(req["path"]), 1 if "range" in req else 0,
            first, last, c_string(req["wire"])))
    out.append("};")
    out.append("")

    listings, entries = [], []
    for fixture in contract["fixtures"]:
        fid = fixture["id"]
        data = encoded[fid]
        out.append("static const unsigned char BlorgContractFixture_%s[] =" % fid)
        out.append("{")
        out.append(byte_rows(data, "    "))
        out.append("};")
        out.append("")
        if fixture["root_type"].endswith(".Directory"):
            files = fixture["data"]["files"]
            subdirs = fixture["data"]["subdirectories"]
            # A zero-length array is not valid C, so empty lists get a null pointer.
            if files:
                out.append("static const BLORG_CONTRACT_FILE BlorgContractFixture_%s_Files[] =" % fid)
                out.append("{")
                for f in files:
                    out.append("    { %s, %dULL, %dULL, %dULL, %dULL }," % (
                        c_wide_string(f["name"]), f["size"], f["created"], f["modified"], f["accessed"]))
                out.append("};")
                out.append("")
            if subdirs:
                out.append("static const BLORG_CONTRACT_SUBDIR BlorgContractFixture_%s_SubDirs[] =" % fid)
                out.append("{")
                for d in subdirs:
                    out.append("    { %s, %dULL, %dULL, %dULL }," % (
                        c_wide_string(d["name"]), d["created"], d["modified"], d["accessed"]))
                out.append("};")
                out.append("")
            listings.append("    { %s, BlorgContractFixture_%s, sizeof(BlorgContractFixture_%s), %s, %d, %s, %d }," % (
                c_string(fid), fid, fid,
                ("BlorgContractFixture_%s_Files" % fid) if files else "NULL", len(files),
                ("BlorgContractFixture_%s_SubDirs" % fid) if subdirs else "NULL", len(subdirs)))
        else:
            d = fixture["data"]
            entries.append("    { %s, BlorgContractFixture_%s, sizeof(BlorgContractFixture_%s), %dULL, %dULL, %dULL, %dULL, %d }," % (
                c_string(fid), fid, fid, d["size"], d["created"], d["modified"], d["accessed"], 1 if d["directory"] else 0))

    out.append("static const BLORG_CONTRACT_LISTING BlorgContractListings[] =")
    out.append("{")
    out.extend(listings)
    out.append("};")
    out.append("")
    out.append("static const BLORG_CONTRACT_ENTRY BlorgContractEntries[] =")
    out.append("{")
    out.extend(entries)
    out.append("};")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# generated/blorg_contract.rs
# ---------------------------------------------------------------------------

def render_rust(contract: dict, encoded: dict[str, bytes]) -> str:
    v = contract["version"]
    t = contract["transport"]
    routes = route_by_id(contract)
    out = [
        "// " + BANNER,
        "//",
        "// The server-rs <-> BlorgFS wire contract, for server-rs to `include!`.",
        "",
        "pub const VERSION_MAJOR: u32 = %d;" % v["major"],
        "pub const VERSION_MINOR: u32 = %d;" % v["minor"],
        "",
        "/// Query parameter carrying the request path.",
        "pub const QUERY_PATH: &str = %s;" % _rust_escape(t["query_path_key"]),
        "pub const MAX_BODY_BYTES: u64 = %d;" % t["max_body_bytes"],
        "pub const MAX_HEADER_BYTES: u64 = %d;" % t["max_header_bytes"],
        "",
        "pub mod route {",
    ]
    for route in contract["routes"]:
        out.append("    pub const %s: &str = %s;" % (route["id"], _rust_escape(route["path"])))
    out.append("}")
    out.append("")
    out.append("/// Success status per route, then the error statuses.")
    out.append("pub mod status {")
    for route in contract["routes"]:
        out.append("    pub const %s_OK: u16 = %d;" % (route["id"], route["success_status"]))
    for error in contract["error_statuses"]:
        out.append("    pub const %s: u16 = %d;" % (error["id"], error["status"]))
    out.append("}")
    out.append("")
    out.append("pub struct Behaviour {")
    out.append("    pub id: &'static str,")
    out.append("    pub title: &'static str,")
    out.append("    pub enforced: bool,")
    out.append("}")
    out.append("")
    out.append("pub const BEHAVIOURS: &[Behaviour] = &[")
    for b in contract["behaviours"]:
        out.append("    Behaviour { id: %s, title: %s, enforced: %s }," % (
            _rust_escape(b["id"]), _rust_escape(b["title"]), "true" if b["status"] == "enforced" else "false"))
    out.append("];")
    out.append("")
    out.append("pub struct Request {")
    out.append("    pub id: &'static str,")
    out.append("    pub route: &'static str,")
    out.append("    /// As the driver receives it from Windows.")
    out.append("    pub path: &'static str,")
    out.append("    /// Inclusive byte range.")
    out.append("    pub range: Option<(u64, u64)>,")
    out.append("    /// The exact bytes the driver sends.")
    out.append("    pub wire: &'static [u8],")
    out.append("}")
    out.append("")
    out.append("pub const REQUESTS: &[Request] = &[")
    for req in contract["requests"]:
        rng = "Some((%d, %d))" % tuple(req["range"]) if "range" in req else "None"
        out.append("    Request { id: %s, route: route::%s, path: %s, range: %s, wire: %s.as_bytes() }," % (
            _rust_escape(req["id"]), req["route"], _rust_escape(req["path"]), rng, _rust_escape(req["wire"])))
    out.append("];")
    out.append("")
    out.append("pub struct File {")
    out.append("    pub name: &'static str,")
    out.append("    pub size: u64,")
    out.append("    pub created: u64,")
    out.append("    pub modified: u64,")
    out.append("    pub accessed: u64,")
    out.append("}")
    out.append("")
    out.append("pub struct Subdirectory {")
    out.append("    pub name: &'static str,")
    out.append("    pub created: u64,")
    out.append("    pub modified: u64,")
    out.append("    pub accessed: u64,")
    out.append("}")
    out.append("")
    out.append("pub struct Listing {")
    out.append("    pub id: &'static str,")
    out.append("    /// Encoded by flatc, the reference encoder.")
    out.append("    pub bytes: &'static [u8],")
    out.append("    pub files: &'static [File],")
    out.append("    pub subdirectories: &'static [Subdirectory],")
    out.append("}")
    out.append("")
    out.append("pub struct Entry {")
    out.append("    pub id: &'static str,")
    out.append("    /// Encoded by flatc, the reference encoder.")
    out.append("    pub bytes: &'static [u8],")
    out.append("    pub size: u64,")
    out.append("    pub created: u64,")
    out.append("    pub modified: u64,")
    out.append("    pub accessed: u64,")
    out.append("    pub directory: bool,")
    out.append("}")
    out.append("")

    listings, entries = [], []
    for fixture in contract["fixtures"]:
        fid = fixture["id"]
        data = encoded[fid]
        bytes_literal = "&[\n%s\n    ]" % byte_rows(data, "        ")
        d = fixture["data"]
        if fixture["root_type"].endswith(".Directory"):
            files = "".join(
                "            File { name: %s, size: %d, created: %d, modified: %d, accessed: %d },\n" % (
                    _rust_escape(f["name"]), f["size"], f["created"], f["modified"], f["accessed"])
                for f in d["files"])
            subdirs = "".join(
                "            Subdirectory { name: %s, created: %d, modified: %d, accessed: %d },\n" % (
                    _rust_escape(s["name"]), s["created"], s["modified"], s["accessed"])
                for s in d["subdirectories"])
            listings.append(
                "    Listing {\n        id: %s,\n        bytes: %s,\n        files: &[\n%s        ],\n        subdirectories: &[\n%s        ],\n    }," % (
                    _rust_escape(fid), bytes_literal.replace("\n    ]", "\n        ]"), files, subdirs))
        else:
            entries.append(
                "    Entry {\n        id: %s,\n        bytes: %s,\n        size: %d,\n        created: %d,\n        modified: %d,\n        accessed: %d,\n        directory: %s,\n    }," % (
                    _rust_escape(fid), bytes_literal.replace("\n    ]", "\n        ]"), d["size"], d["created"], d["modified"], d["accessed"],
                    "true" if d["directory"] else "false"))

    out.append("pub const LISTINGS: &[Listing] = &[")
    out.extend(listings)
    out.append("];")
    out.append("")
    out.append("pub const ENTRIES: &[Entry] = &[")
    out.extend(entries)
    out.append("];")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------

def validate(contract: dict) -> None:
    """Catch contract mistakes before they become generated code."""
    routes = route_by_id(contract)
    ids = [b["id"] for b in contract["behaviours"]]
    if len(ids) != len(set(ids)):
        sys.exit("duplicate behaviour id")
    for b in contract["behaviours"]:
        if b["status"] not in ("enforced", "gap"):
            sys.exit("%s: status must be enforced or gap" % b["id"])
    for req in contract["requests"]:
        route = routes[req["route"]]
        expected = encode_request(contract, route["path"], req["path"], req["host"], req.get("range"))
        if expected != req["wire"]:
            sys.exit("request %s: wire does not follow transport.path_encoding\n  want %r\n  have %r" % (
                req["id"], expected, req["wire"]))
    for fixture in contract["fixtures"]:
        if fixture["root_type"].endswith(".Directory"):
            names = [e["name"] for e in fixture["data"]["files"]] + [e["name"] for e in fixture["data"]["subdirectories"]]
            if len(names) != len(set(names)):
                sys.exit("fixture %s breaks B06: duplicate name" % fixture["id"])
            for group in ("files", "subdirectories"):
                group_names = [e["name"].encode("utf-8") for e in fixture["data"][group]]
                if group_names != sorted(group_names):
                    sys.exit("fixture %s breaks B06: %s not in byte-wise name order" % (fixture["id"], group))


SAFE = set(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~")


def percent_encode(path: str) -> str:
    return "".join(chr(b) if b in SAFE else "%%%02X" % b for b in path.encode("utf-8"))


def encode_request(contract: dict, route_path: str, path: str, host: str, rng) -> str:
    key = contract["transport"]["query_path_key"]
    wire = "GET %s?%s=%s HTTP/1.1\r\nHost: %s\r\nConnection: keep-alive\r\n" % (route_path, key, percent_encode(path), host)
    if rng:
        wire += "Range: bytes=%d-%d\r\n" % (rng[0], rng[1])
    return wire + "\r\n"


def render_all(contract: dict, out_dir: Path) -> None:
    (out_dir / "fixtures").mkdir(parents=True, exist_ok=True)
    (out_dir / "generated").mkdir(parents=True, exist_ok=True)
    encoded = encode_fixtures(contract, out_dir)
    outputs = {
        "generated/blorg_contract.h": render_c_header(contract),
        "generated/blorg_contract_fixtures.h": render_c_fixtures(contract, encoded),
        "generated/blorg_contract.rs": render_rust(contract, encoded),
    }
    for rel, text in outputs.items():
        (out_dir / rel).write_bytes(text.encode("ascii"))


GENERATED = ["generated/blorg_contract.h", "generated/blorg_contract_fixtures.h", "generated/blorg_contract.rs"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = parser.parse_args()

    contract = load_contract()
    validate(contract)

    if not args.check:
        render_all(contract, ROOT)
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        render_all(contract, Path(tmp))
        expected = GENERATED + ["fixtures/%s.bin" % f["id"] for f in contract["fixtures"]]
        stale = [rel for rel in expected
                 if not (ROOT / rel).exists() or (ROOT / rel).read_bytes() != (Path(tmp) / rel).read_bytes()]
    if stale:
        print("stale generated files (run python3 tools/generate.py and commit):", file=sys.stderr)
        for rel in stale:
            print("  " + rel, file=sys.stderr)
        return 1
    print("generated files are up to date with contract.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
